# Generated by Django 4.2.2 on 2023-06-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('News', 'Новости'), ('Post', 'Статья')], max_length=4),
        ),
    ]
