# Generated by Django 4.2.2 on 2023-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('post', 'Статья')], max_length=4),
        ),
    ]
